// Defense presentation
#set page(paper: "presentation-16-9", margin: (x: 18mm, y: 12mm))
#set text(font: "New Computer Modern", size: 15pt, lang: "en")
#set par(justify: false, leading: 0.55em)

#let blue = rgb("#24476f")
#let teal = rgb("#2f7f79")
#let green = rgb("#3d7a4f")
#let red = rgb("#a94a4a")
#let gray = rgb("#5f6670")
#let pale_blue = rgb("#eef4f8")
#let pale_green = rgb("#edf7f0")
#let pale_red = rgb("#f8eeee")
#let line_gray = rgb("#d7dce2")

#let slide_title(body) = {
  text(size: 23pt, weight: "bold", fill: blue)[#body]
  v(0.25em)
  line(length: 100%, stroke: 0.8pt + line_gray)
  v(0.45em)
}

#let accent(body) = text(fill: teal, weight: "bold")[#body]
#let small(body) = text(size: 12pt, fill: gray)[#body]

#let tag(body, fill: pale_blue, stroke: blue) = rect(
  inset: (x: 7pt, y: 4pt),
  radius: 3pt,
  fill: fill,
  stroke: 0.7pt + stroke,
)[#body]

#let takeaway(body) = rect(
  width: 100%,
  inset: 10pt,
  radius: 4pt,
  fill: pale_green,
  stroke: 0.8pt + green,
)[#body]

#let footer() = {
  place(bottom + right, dx: -0.25cm, dy: 0.25cm,
    text(size: 9pt, fill: rgb("#8b929a"))[
      #context counter(page).display()
    ]
  )
}

// ============================================================
// 1. Title
// ============================================================

#v(1fr)
#align(center)[
  #text(size: 30pt, weight: "bold", fill: blue)[
    Statistical Inference for Linear \
    Stochastic Approximation with \
    Richardson--Romberg Extrapolation
  ]
  #v(1.3em)
  #text(size: 18pt)[Danil Gainanov]
  #v(0.5em)
  #text(size: 13pt, fill: gray)[Supervisor: Ilya Levin]
  #v(0.4em)
  #text(size: 12pt, fill: gray)[Master's thesis defense, 2026]
]
#v(1fr)
#footer()

// ============================================================
// 2. Motivation
// ============================================================
#pagebreak()

#slide_title[Motivation: Confidence Intervals for Dependent Algorithms]

#grid(columns: (1fr, 1fr, 1fr), column-gutter: 12pt,
  tag(fill: pale_blue, stroke: blue)[
    *Stochastic approximation* \
    Updates arrive sequentially and depend on data generated by a Markov chain.
  ],
  tag(fill: pale_red, stroke: red)[
    *Constant step size* \
    Stable and fast in practice, but leaves a persistent step-size bias.
  ],
  tag(fill: pale_green, stroke: green)[
    *Statistical inference* \
    We need confidence intervals, not only point estimates.
  ],
)

#v(0.9em)

The main difficulty is not only convergence:

#align(center)[
  #text(size: 19pt, weight: "bold")[
    biased center + dependent noise = unreliable confidence intervals
  ]
]

#v(0.8em)

#takeaway[
  This thesis studies how Richardson--Romberg extrapolation can remove the
  leading constant-step bias while preserving the usual long-run covariance
  target for inference.
]

#footer()

// ============================================================
// 3. Model
// ============================================================
#pagebreak()

#slide_title[Linear Stochastic Approximation]

We observe a Markov chain $Z_1, Z_2, dots$ and run

$ theta_k = theta_(k-1) - alpha (A(Z_k) theta_(k-1) - b(Z_k)). $

#v(0.3em)

The target is the equilibrium of the averaged problem:

$ theta^* = overline(A)^(-1) overline(b), quad
   overline(A) = integral A(z) pi(d z), quad
   overline(b) = integral b(z) pi(d z). $

#v(0.6em)

#grid(columns: (1fr, 1fr), column-gutter: 14pt,
  [
    *Why average iterates?* \
    Polyak--Ruppert averaging reduces variance and gives the standard
    $sqrt(n)$ scale.
  ],
  [
    *Why constant steps?* \
    They are practical and stable, but the estimator is generally centered at
    $theta^* + O(alpha)$ instead of $theta^*$.
  ],
)

#v(0.4em)

#takeaway[
  If the interval center is shifted by the step-size bias, even a good variance
  estimate cannot restore correct coverage.
]

#footer()

// ============================================================
// 4. Richardson--Romberg
// ============================================================
#pagebreak()

#slide_title[Richardson--Romberg in the Step Size]

Run two averaged LSA trajectories on the #accent[same Markov chain path]:

$ overline(theta)_n^("RR") =
    2 overline(theta)_n^((alpha)) - overline(theta)_n^((2 alpha)). $

#v(0.4em)

#grid(columns: (1fr, 0.16fr, 1fr), column-gutter: 10pt,
  [
    *Single constant step* \
    $overline(theta)_n^((alpha)) approx theta^* + alpha Delta + "noise"$
  ],
  align(center + horizon)[#text(size: 26pt, fill: teal)[$arrow.r.long$]],
  [
    *RR combination* \
    $2(alpha Delta) - (2 alpha Delta) = 0$
  ],
)

#v(0.8em)

#takeaway[
  RR is used to move the center of the confidence interval, not to estimate the
  covariance. Covariance estimation is a separate problem.
]

#v(0.4em)

#small[The shared trajectory is important: the two branches have highly
correlated noise, so the extrapolation targets bias rather than adding an
independent simulation error.]

#footer()

// ============================================================
// 5. Inference target
// ============================================================
#pagebreak()

#slide_title[What Distribution Should We Approximate?]

For a direction $u$, the practical statistic is

$ sqrt(m) u^top (overline(theta)_(n,n_0)^("RR") - theta^*),
  quad m = n - n_0. $

#v(0.5em)

The target variance is the standard Markovian long-run covariance:

$ Sigma_infinity =
  overline(A)^(-1) Sigma_epsilon^("M") overline(A)^(-T). $

#v(0.5em)

#grid(columns: (1fr, 1fr), column-gutter: 14pt,
  tag(fill: pale_blue, stroke: blue)[
    *Markovian noise* \
    $Sigma_epsilon^("M")$ includes serial correlations of
    $epsilon(Z_k)$.
  ],
  tag(fill: pale_green, stroke: green)[
    *Inference goal* \
    Approximate the scalar statistic by
    $cal(N)(0, u^top Sigma_infinity u)$.
  ],
)

#footer()

// ============================================================
// 6. Main result
// ============================================================
#pagebreak()

#slide_title[Main Theoretical Result]

Under uniform geometric ergodicity, Lyapunov stability, bounded noise, and a
mixing-scale burn-in, the burned-in RR average satisfies a Berry--Esseen bound.

#v(0.3em)

#align(center)[
  #rect(inset: 12pt, radius: 4pt, fill: pale_blue, stroke: 0.8pt + blue)[
    $ d_K (
      sqrt(m) u^top (overline(theta)_(n,n_0)^("RR") - theta^*) / sigma(u),
      cal(N)(0,1)
    )
    <= C(u,c,theta_0) "polylog"(n) n^(-1/4). $
  ]
]

#v(0.6em)

Balanced scale:

$ alpha = c n^(-1/2),
  quad n_0 approx (alpha a)^(-1) log^2 n,
  quad sigma^2(u) = u^top Sigma_infinity u. $

#v(0.4em)

#takeaway[
  The theorem turns the RR averaged estimator into a valid normal-approximation
  object for scalar confidence intervals.
]

#footer()

// ============================================================
// 7. Proof architecture
// ============================================================
#pagebreak()

#slide_title[Proof Idea Without the Technical Details]

#grid(columns: (1fr, 1fr), column-gutter: 14pt,
  [
    *1. Deterministic RR weights* \
    The leading averaged error is a weighted sum of Markovian noise. RR changes
    the deterministic kernel, and the kernel is close to $overline(A)^(-1)$.

    #v(0.5em)

    *2. Markovian noise reduction* \
    A Poisson-equation decomposition converts the main dependent sum into a
    martingale term plus controlled boundary terms.
  ],
  [
    *3. Variance comparison* \
    The finite-window variance of the RR statistic is compared with
    $Sigma_infinity$.

    #v(0.5em)

    *4. Remainder control and burn-in* \
    Misadjustment, random initial products, and deterministic transients are
    shown to be smaller than the leading Gaussian term.
  ],
)

#v(0.6em)

#takeaway[
  The proof separates what RR cancels from what normal approximation and mixing
  have to control.
]

#footer()

// ============================================================
// 8. Practical intervals
// ============================================================
#pagebreak()

#slide_title[From Theory to Confidence Intervals]

In practice $Sigma_infinity$ is unknown, so the long-run variance must be
estimated from one dependent trajectory.

#v(0.3em)

#grid(columns: (1fr, 1fr), column-gutter: 14pt,
  tag(fill: pale_blue, stroke: blue)[
    *OBM* \
    Overlapping batch means estimate the long-run variance of the projected
    trajectory.
  ],
  tag(fill: pale_green, stroke: green)[
    *OBM-LW / lugsail* \
    A signed two-window correction can reduce the leading OBM window bias.
  ],
)

#v(0.7em)

#align(center)[
  #text(size: 18pt, weight: "bold")[
    RR changes the center; OBM and lugsail change the width.
  ]
]

#v(0.6em)

#small[
  The thesis proves the distributional approximation for the RR estimator.
  A full non-asymptotic theory for OBM and lugsail along RR trajectories is
  left as a separate future direction.
]

#footer()

// ============================================================
// 9. Experiments setup
// ============================================================
#pagebreak()

#slide_title[Numerical Experiments]

#table(
  columns: (1.15fr, 2.2fr),
  inset: 7pt,
  stroke: 0.45pt + line_gray,
  fill: (x, y) => if y == 0 { pale_blue },
  [*Quantity*], [*Main setup*],
  [Problem class], [Finite-state Markovian LSA],
  [Dimension and states], [$d=5$, 10 Markov states],
  [Monte Carlo design], [100 problems, 100 trajectories per problem],
  [Trajectory length], [$T = 10^6$],
  [RR stepsizes], [$alpha in {0.2, 0.02}$ in the main comparison],
  [Inference], [95% scalar intervals in a random projection direction],
  [Variance estimators], [Batch means, OBM, OBM-LW, MSB, and oracle diagnostics],
)

#v(0.4em)

#takeaway[
  The experiments are designed to separate the point-estimator bias from the
  long-run variance estimation error.
]

#footer()

// ============================================================
// 10. Main comparison
// ============================================================
#pagebreak()

#slide_title[Main Comparison: RR Fixes the Center]

#grid(columns: (1.0fr, 1.15fr), column-gutter: 14pt,
  [
    #table(
      columns: (1.55fr, 0.65fr, 0.65fr),
      inset: 5pt,
      align: (left, center, center),
      stroke: 0.4pt + line_gray,
      fill: (x, y) => if y == 0 { pale_blue } else if y == 3 or y >= 6 { pale_green },
      [*Method*], [*L2*], [*Cov.*],
      [$alpha=0.2$ const.], [$26.67$], [$0.5%$],
      [$alpha=0.02$ const.], [$13.93$], [$40.5%$],
      [RR const.], [$4.52$], [$94.0%$],
      [Diminishing], [$6.80$], [$90.0%$],
      [PR + OBM], [$5.35$], [$92.0%$],
      [RR + OBM], [$4.52$], [$95.0%$],
      [RR + OBM-LW], [$4.52$], [$95.0%$],
    )

    #small[L2 is reported in units of $10^(-3)$; medians over 100 problems.]
  ],
  [
    #image("figures/experiments/main_methods_comparison.svg", width: 100%)
  ],
)

#v(0.2em)

#takeaway[
  The coverage gain is not achieved by widening intervals: RR mainly improves
  the interval center by reducing step-size bias.
]

#footer()

// ============================================================
// 11. Stepsize and oracle diagnostics
// ============================================================
#pagebreak()

#slide_title[Diagnostics: Stepsize and Variance Estimation]

#table(
  columns: (1.15fr, 1.75fr, 0.8fr, 0.8fr),
  inset: 6pt,
  align: (left, left, center, center),
  stroke: 0.45pt + line_gray,
  fill: (x, y) => if y == 0 { pale_blue } else { if y == 1 or y == 2 or y == 3 { pale_green } },
  [*RR pair*], [*Single-step coverage*], [*RR L2*], [*RR cov.*],
  [$(0.04,0.02)$], [$0.04$: $92.0%$; $0.02$: $94.0%$], [$2.97$], [$94.0%$],
  [$(0.10,0.05)$], [$0.10$: $86.0%$; $0.05$: $91.5%$], [$2.97$], [$94.0%$],
  [$(0.20,0.10)$], [$0.20$: $67.5%$; $0.10$: $86.0%$], [$2.97$], [$94.0%$],
)

#v(0.5em)

For the largest adjacent pair, oracle and practical variance intervals are
almost identical:

#align(center)[
  #tag(fill: pale_green, stroke: green)[
    RR + oracle variance: 95.0% coverage; RR + OBM: 95.0%; RR + MSB: 95.0%.
  ]
]

#v(0.4em)

#small[
  In this regime, long-run variance estimation is not the bottleneck; the key
  effect is still the RR bias cancellation in the center.
]

#footer()

// ============================================================
// 12. OBM and lugsail
// ============================================================
#pagebreak()

#slide_title[Variance Estimation: When Does Lugsail Help?]

#grid(columns: (1.0fr, 1.2fr), column-gutter: 14pt,
  [
    *OBM can be too narrow* when the Bartlett-window bias is negative.

    #v(0.4em)

    *Lugsail can help* by cancelling the leading window-bias term, especially
    for smaller block sizes or more persistent trajectories.

    #v(0.4em)

    *But it is not automatic:* large blocks can make the signed correction
    unstable.
  ],
  [
    #image("figures/experiments/blocksize_lugsail_diagnostics.svg", width: 100%)
  ],
)

#v(0.2em)

#takeaway[
  Step-size RR and lugsail OBM solve different problems: center bias versus
  variance-estimator window bias.
]

#footer()

// ============================================================
// 13. Contributions
// ============================================================
#pagebreak()

#slide_title[Contributions and Limitations]

#grid(columns: (1fr, 1fr), column-gutter: 16pt,
  [
    *Main contributions*
    - Formulated RR-averaged constant-step LSA inference under Markovian noise.
    - Proved a scalar Berry--Esseen bound at the balanced scale.
    - Transferred the result from stationary starts to burned-in deterministic starts.
    - Verified the bias-correction mechanism in finite-state experiments.
  ],
  [
    *Limitations and future work*
    - Full multivariate confidence regions.
    - Non-asymptotic OBM and lugsail theory along RR trajectories.
    - Sharper dependence on mixing time and stability constants.
    - More diagnostics for slow mixing and matrix covariance estimates.
  ],
)

#v(0.5em)

#takeaway[
  The central message: RR makes constant-step LSA statistically usable by
  correcting the center, while standard long-run variance tools handle the
  interval width.
]

#footer()

// ============================================================
// 14. Thank you
// ============================================================
#pagebreak()

#v(2fr)
#align(center)[
  #text(size: 34pt, weight: "bold", fill: blue)[Thank you!]
  #v(0.9em)
  #text(size: 20pt, fill: gray)[Questions?]
]
#v(2fr)
#footer()
