#let english-abstract = [
This thesis studies statistical inference for constant-stepsize linear stochastic
approximation with Markovian noise and Richardson--Romberg extrapolation. The
goal of the work is to describe how confidence statements can be constructed for
Polyak--Ruppert averaged iterates when the observations are generated by a
dependent Markov chain and the algorithm is run with non-vanishing step sizes.
The main tasks are to formulate the linear stochastic approximation model,
separate the deterministic and stochastic components of the averaged error,
analyze the effect of Richardson--Romberg coupling of the step sizes $alpha$ and
$2 alpha$, and connect the resulting distributional approximation with
long-run variance estimation.

The methodology combines finite-sample decompositions of linear recursions,
Lyapunov stability arguments, Poisson-equation tools for geometrically ergodic
Markov chains, martingale approximation, Berry--Esseen type bounds, and
overlapping batch-means variance estimation. The empirical part is based on
simulations for representative linear stochastic approximation models. These
experiments compare ordinary averaging with the Richardson--Romberg estimator
and examine the interaction between bias reduction and covariance estimation.

The main result is a non-asymptotic normal approximation for scalar projections
of the Richardson--Romberg averaged estimator, together with the identification
of the covariance target
$Sigma_infinity = overline(A)^(-1) Sigma_epsilon^(M) overline(A)^(-T)$. The
analysis shows which terms are cancelled by extrapolation, which residual terms
are controlled by mixing and stability, and why burn-in and variance estimation
are essential for confidence intervals. The numerical results support the
theoretical conclusion that Richardson--Romberg extrapolation can substantially
reduce step-size bias while preserving the standard inference target when the
covariance estimator is calibrated appropriately.
]

#let russian-abstract = [
В работе рассматривается статистический вывод для линейной стохастической
аппроксимации с постоянным шагом, марковским шумом и экстраполяцией
Ричардсона--Ромберга. Цель работы состоит в описании доверительных утверждений
для усредненных по Поляку--Рупперту итераций, когда наблюдения порождаются
зависимой марковской цепью, а алгоритм использует ненулевые постоянные шаги.
Основные задачи включают формализацию
модели линейной стохастической аппроксимации, разложение усредненной ошибки на
детерминированные и случайные компоненты, анализ влияния совместного
использования шагов $alpha$ и $2 alpha$ в схеме Ричардсона--Ромберга, а также
связь полученного распределительного приближения с оцениванием долгосрочной
ковариации.

Методология работы основана на конечновыборочных разложениях линейных
рекурсий, устойчивости Ляпунова, уравнениях Пуассона для геометрически
эргодических марковских цепей, мартингальных приближениях, оценках типа
Берри--Эссеена и оценивании ковариации методом перекрывающихся блочных средних.
Эмпирическая часть опирается на эксперименты для типовых моделей линейной
стохастической аппроксимации. В экспериментах сравниваются обычное
усреднение с постоянным шагом и оценка Ричардсона--Ромберга, а также
исследуется связь между уменьшением смещения и оценкой асимптотической
ковариации.

Основным результатом является неасимптотическое нормальное приближение для
скалярных проекций усредненной оценки Ричардсона--Ромберга и выделение
ковариационной цели
$Sigma_infinity = overline(A)^(-1) Sigma_epsilon^(M) overline(A)^(-T)$. Анализ
показывает, какие члены сокращаются за счет экстраполяции, какие остаточные
члены контролируются смешиванием и устойчивостью, а также почему разогрев и
оценка ковариации необходимы для построения доверительных интервалов. Численные
результаты подтверждают, что
экстраполяция Ричардсона--Ромберга может существенно уменьшать смещение,
связанное с шагом, при сохранении стандартной цели статистического вывода при
корректной настройке оценки ковариации.
]
