#import "defs.typ": *

#include "burn_in_transfer/00_preamble.typ"
#include "burn_in_transfer/01_target_statistic_and_normalization.typ"
#include "burn_in_transfer/02_burned_in_deterministic_weights.typ"
#include "burn_in_transfer/03_closed_forms_and_weight_bounds.typ"
#include "burn_in_transfer/04_deterministic_transient.typ"
#include "burn_in_transfer/05_variance_proxy.typ"
#include "burn_in_transfer/06_poisson_martingale_approximation.typ"
#include "burn_in_transfer/07_predictable_variance_comparison.typ"
#include "burn_in_transfer/08_startup_transfer_augmented_remainders.typ"
#include "burn_in_transfer/09_depth_two_misadjustment_bound.typ"
#include "burn_in_transfer/10_martingale_berry_esseen.typ"
#include "burn_in_transfer/11_finite_window_smoothing_assembly.typ"
#include "burn_in_transfer/12_balanced_burn_in_berry_esseen.typ"
